# Generated by Django 2.1 on 2018-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Artigo')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
